### ISSUE TITLE
java.io.Exception: ClearText http traffic

### ISSUE THREAD

**Issue by auben2k** [TheBotBox/Horoscope-API#1]
I am attempting to use this API as apart of my final project for my android development course. I am running into an issue when requesting horoscopes. Screenshots below. Please get back to me, thanks!
![Debug1](https://user-images.githubusercontent.com/1340359/55841574-ae5bfa80-5afd-11e9-8aad-a03e40ed6ce2.PNG)

**Comment by exceptionSPG** [comment]
I got the same problem. Did you get the solution?
