### ISSUE TITLE
Importing does not work

### ISSUE THREAD

**Issue by LennoxCode** [TheBotBox/Horoscope-API#5]
hello,
I am currently trying to use your api to write a simple discord bot, who returns your daily horoscope upon request. My main problem is, that importing your files does not work, and I cant use any of the function calls. Some help how to resolve this issue would be greatly appreciated. thanks in advance:)

my file looks like this

plugins {
    id 'java'
}

group 'github.LennoxCode'
version '1.0-SNAPSHOT'

repositories {
    maven {
        url  "https://dl.bintray.com/boxbotbarry/maven"
    }
    mavenCentral()
    jcenter()
}

dependencies {
    compile 'org.javacord:javacord:3.0.5'
    implementation 'the.bot.box:horoscope-api:1.0.2'
    //compile  fileTree(dir: 'libs', include: ['*.jar'])
}

**Comment by TheBotBox** [comment]
Hi, 
Is IDE able to compile your code ? or is it throwing some error ?

**Comment by LennoxCode** [comment]
the build.gradle file does compile fine. The problem arises, if I try to use the functions or classes you created.

**Comment by TheBotBox** [comment]
let me create a new project and try implementing the same.

**Comment by TheBotBox** [comment]
Everything seems fine to me. 
I just now create a new project and added the Gradle dependencies. Working absolutely fine,
No need to call 

> maven {
> url "https://dl.bintray.com/boxbotbarry/maven"
> }

all you have to do is open your project's build.gradle and add the below line in dependencies. 

> implementation 'the.bot.box:horoscope-api:1.0.2' 

if you are adding the dependency in another library and then accessing its classes in your project then do like this

> api 'the.bot.box:horoscope-api:1.0.2'

**Comment by LennoxCode** [comment]
I also started a new project and tried to import it with the following lines:
![screen](https://user-images.githubusercontent.com/64899757/82457781-21cc8b80-9ab6-11ea-9459-7ecd1d88577c.PNG)
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    maven {
        url "https://dl.bintray.com/boxbotbarry/maven"
    }
}

dependencies {
    //testCompile group: 'junit', name: 'junit', version: '4.12'
    implementation 'the.bot.box:horoscope-api:1.0.2'
}

the gradle files build fine, but I still cant import the classes. I just noticed that the external libary end with .aar and not .jar

**Comment by TheBotBox** [comment]
Yes, the external library will end up with **.aar** only as it is an android artifact based on java. So, it will end up with **.aar** instead of **.jar**
Also, I can see now and I am sorry for that, but this project is not compatible for java but for android only. (Will update my project description)

**Comment by LennoxCode** [comment]
That makes a lot of sense in hindsight. I almost thought that I am too stupid too import your project, but that explains my struggle.
Thank you for your time anyway:)
