### ISSUE TITLE
java.io.Exception: ClearText http traffic

### ISSUE THREAD

**Issue by shuklanikk** [TheBotBox/Horoscope-API#6]
I am attempting to use this API as apart of my project for my android , got  issue when requesting horoscopes. Screenshots below.

thanks!

![Screenshot_2020-08-26-09-16-29-72_a8b97be402efee03e8e59ced21cf28a1](https://user-images.githubusercontent.com/43662110/91258643-73a64100-e78a-11ea-8626-eb891d1d189b.jpg)

**Comment by TheBotBox** [comment]
Make following changes in your project's manifest.
```
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>
```

Starting with Android 9 (API level 28), cleartext support is disabled by default.
